### ISSUE TITLE
Do notifications work?

### ISSUE THREAD

**Issue by markmandel** [syvanpera/xmonad-cinnamon#1]
Thanks for putting this together! I'm in the process of taking it for a spin.

I don't seem to be getting notifications though. Is that a known issue?

Do we have any workarounds?

**Comment by syvanpera** [comment]
Hi, sorry for some reason I don't seem to get a notification when there are issues posted here. This answer might come too late as it's been a while since you asked, but the answer is I don't know. Or I should say that I don't know about the cinnamon notification daemon stuff etc. I use dunst myself

**Comment by markmandel** [comment]
Ah! No worries at all - I also use Dunst now as well :+1: Looks like it is a known issue - the cinnamon notification system doesn't come through.
